### PR TITLE
Korean translation work of ics spec

### PR DESCRIPTION
**Pull request by zero1ne**
related with: #253 

We are in the process of translating the documents in the spec folder.
Please check the finished translation. @mossid @cwgoes 

- ics-001-ics-standard/README.md
- ics-025-handler-interface/README.md
- ics-026-routing-module/README.md

If we create a PR to all the files at once, it seems too unmanageable.
So we're going to make a PR at several times with 3 or 4 translated files.

### CODE REVIEW

**Comment by cwgoes** [comment]
Thanks so much for the translation - again I think I am going to have to ask @mossid to review this.

**Comment by dogemos** [comment]
I can help review some of these documents if you'd like @mossid @cwgoes

**Comment by cwgoes** [comment]
> I can help review some of these documents if you'd like @mossid @cwgoes

That would be fantastic, actually.

**Comment by dogemos** [comment]
I've suggested some changes in wording for clarity here (https://github.com/DE-labtory/ics/pull/21). @zero1ne

The translation is fantastic. Thank you so much for your work!

**Comment by cwgoes** [comment]
Please move the files to `translation/ko`.

**Comment by junbeomlee** [comment]
thx :)

**Comment by zero1ne** [comment]
Thank you for your review. @dogemos
I checked your suggestions and merge your commit.

**Comment by cwgoes** [comment]
@dogemos @mossid - do you think this is ready to merge?

**Comment by dogemos** [comment]
Looks good to me @cwgoes.

Thank you @zero1ne!

**Pull request merged**
