### PR TITLE
korean translation work applied review comments

### PR DESCRIPTION
**Pull request by junbeomlee**
@mossid 
Thank you for your review.

@cwgoes 
I applied PR(#279) review comment.

### CODE REVIEW

**Comment by cwgoes** [comment]
Should this replace #279 then?

**Comment by junbeomlee** [comment]
Not all of them, but only some of the reviews. Only some of the documents that received a review were modified and uploaded. If @mossid  reviews further on the rest of #279, I'll send a new pr for the document that I modified!

**Comment by junbeomlee** [comment]
@mossid plz check this! thank you

**Comment by junbeomlee** [comment]
@mossid

**Comment by cwgoes** [comment]
cc @dogemos if you are feeling inspired

(alas, I am not qualified to review this!)

**Comment by dogemos** [comment]
Looks like @mossid has already reviewed these 3 documents. I've gone through them and haven't noticed any problems.

Just one thing to double-check, Is `ics/ko` where you want the translated documents to be located @cwgoes?

We've gone with `repo/translation/kr` scheme with Gaia and Cosmos-SDK, but open to suggestions.

**Comment by cwgoes** [comment]
> Looks like @mossid has already reviewed these 3 documents. I've gone through them and haven't noticed any problems.
> 
> Just one thing to double-check, Is `ics/ko` where you want the translated documents to be located @cwgoes?
> 
> We've gone with `repo/translation/kr` scheme with Gaia and Cosmos-SDK, but open to suggestions.

That sounds good. I don't know if I can edit this branch, I'll merge it and change the folder.

**Pull request merged**
