### PR TITLE
Simplified Chinese translation (ics/spec/*)

### PR DESCRIPTION
**Pull request by en**
This is an ongoing translation project for the contents of directory ics/spec/*
If you have any suggestions, please leave a comment.

### CODE REVIEW

**Comment by en** [comment]
:mega: call for reviewers, @arthaszeng, @xiangjianmeng, @Satoshi-Kusumoto, @toliuyi, @chengwenxi

**Comment by en** [comment]
hi @cwgoes , we may merge this PR now.

**Comment by Satoshi-Kusumoto** [comment]
@cwgoes I think we may merge this PR.
Also I think we may find a place to write the contact information of the Chinese translation group, what do you think?

**Comment by cwgoes** [comment]
> @cwgoes I think we may merge this PR.
> Also I think we may find a place to write the contact information of the Chinese translation group, what do you think?

Merged. Thanks for the translation. Feel free to add your contact information if you like.

**Pull request merged**
