### PR TITLE
Fix missing hash() in ICS 02

### PR DESCRIPTION
**Pull request by junha1**
I think here `hash()` is needed.

### CODE REVIEW

**Comment by junha1** [comment]
@cwgoes I don't know why, but strangely 'request review' button doesn't appear.

**Comment by cwgoes** [comment]
Hmm, odd.

The lack of `hash` here is intentional; that should instead happen inside the client-specific verification function definitions, that way the implementation of `hash` can vary per-client-type.

**Comment by junha1** [comment]
@cwgoes 
That really make sense. Then `verify_...()` in ICS02 has to be updated with `hash()` I think.

**Comment by cwgoes** [comment]
> @cwgoes
> That really make sense. Then `verify_...()` in ICS02 has to be updated with `hash()` I think.

Yes, it probably does, I suspect I forgot to do that.

**Comment by cwgoes** [comment]
Do you see anywhere `hash()` is missing? ICS 7 has it, e.g. [here](https://github.com/cosmos/ics/tree/master/spec/ics-007-tendermint-client#state-verification-functions).

**Comment by junha1** [comment]
@cwgoes I found something. Regarding `verify_packet_data()` in ICS07, it hashes only `data` of packet, not together with `timeout`. I think we need to add a new parameter `timeout` in `verify_packet_data()` to fix this.

**Comment by cwgoes** [comment]
> @cwgoes I found something. Regarding `verify_packet_data()` in ICS07, it hashes only `data` of packet, not together with `timeout`. I think we need to add a new parameter `timeout` in `verify_packet_data()` to fix this.

The concatenation of data & timeout occurs prior to `verifyPacketCommitment` - see `recvPacket` [here](https://github.com/cosmos/ics/blob/master/spec/ics-004-channel-and-packet-semantics/README.md). Maybe the concatenation should be performed in the client-type-specific code though, did you have a use-case in mind?

**Comment by junha1** [comment]
@cwgoes, Not really, but seems to be worth it to just update.
Btw ICS 02 has to be updated because `hash()` is actually missing there, unlike ICS 07. (Regardless of concat responsibility)

**Comment by cwgoes** [comment]
> @cwgoes, Not really.
> Btw ICS 02 has to be updated because `hash()` is actually missing there, unlike ICS 07. (Regardless of concat responsibility)

Aye, you're right, and thanks for the review!

**Comment by junha1** [comment]
@cwgoes Thanks!

**Pull request merged**
